homeassistant:
  name: Home
  latitude: 50.629078
  longitude: 3.0589089999999715
  elevation: 26
  unit_system: metric
  time_zone: Europe/Paris
  customize: !include customize.yaml

media_player:
  - platform: sonos

  - platform: braviatv
    host: 192.168.1.43

sensor:
  - platform: linky
    username: !secret linky_username
    password: !secret linky_password

  - platform: yr

switch:
  - platform: rfxtrx
    # automatic_add: True
    devices:
      0b110000017016a60a010f70:
        name: Porte
      0b11000663bc0cfe02010f70:
        name: Lumière chambre
      0b11000246bc0cfe07010f70:
        name: Lumière TV
      0b11000212bc0cfe01010f70:
        name: Guirlande

  - platform: command_line
    switches:
      garage:
        command_on: "/usr/bin/curl -X GET http://192.168.1.66/open"
        command_off: "exit 0"
        friendly_name: Garage

vacuum:
  - platform: xiaomi_miio
    host: 192.168.1.44
    token: 4f344b72364c676d5379325439564243

scene:
  - name: "Cosy"
    entities:
      switch.guirlande: on
      switch.lumiere_tv: on
      switch.fibaro_system_fgs213_switch_switch: off

  - name: "TF1"
    entities:
      media_player.sony_bravia_tv:
        source: TF1

  - name: "BFM"
    entities:
      media_player.sony_bravia_tv:
        source: BFM TV

  - name: "Arté"
    entities:
      media_player.sony_bravia_tv:
        source: Arte

rfxtrx:
  device: /dev/ttyUSB0

zwave:
  usb_path: /dev/ttyACM0

google_assistant:
  project_id: roost-d24db
  exposed_domains:
    - switch
    - scene
    - light
    - group
    - media_player
    - climate

# Enables the frontend
frontend:

# Enables configuration UI
config:

http:
  ssl_certificate: /ssl/fullchain.pem
  ssl_key: /ssl/privkey.pem
  # Secrets are defined in the file secrets.yaml
  api_password: !secret http_password
  # Uncomment this if you are using SSL/TLS, running in Docker container, etc.
  # base_url: example.duckdns.org:8123

# Checks for available updates
# Note: This component will send some information about your system to
# the developers to assist with development of Home Assistant.
# For more information, please see:
# https://home-assistant.io/blog/2016/10/25/explaining-the-updater/
updater:
  # Optional, allows Home Assistant developers to focus on popular components.
  # include_used_components: true

# Discover some devices automatically
discovery:

# Allows you to issue voice commands from the frontend in enabled browsers
conversation:

# Enables support for tracking state changes over time
history:

# View all events in a logbook
logbook:

# Enables a map showing the location of tracked devices
map:

# Track the sun
sun:

# Climate (e.g. thermostats) devices
climate:
  - platform: zwave

# Text to speech
tts:
  - platform: google

# Cloud
cloud:

# HomeKit
homekit:

group: !include groups.yaml
automation: !include automations.yaml
script: !include scripts.yaml
