switch.fibaro_system_fgs213_switch_switch_3:
  ignored: true
  polling_intensity: 0
switch.fibaro_system_fgs213_switch_switch_4:
  ignored: true
  polling_intensity: 0
sensor.fibaro_system_fgs213_switch_unknown:
  ignored: true
  polling_intensity: 0
